// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/float64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "github.com/pgbeam/pgbeam-go"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*cacheRuleResource)(nil)
	_ resource.ResourceWithConfigure   = (*cacheRuleResource)(nil)
	_ resource.ResourceWithImportState = (*cacheRuleResource)(nil)
)

type cacheRuleResource struct {
	client *pgbeam.Client
}

type cacheRuleResourceModel struct {
	ID               types.String  `tfsdk:"id"`
	ProjectID        types.String  `tfsdk:"project_id"`
	DatabaseID       types.String  `tfsdk:"database_id"`
	QueryHash        types.String  `tfsdk:"query_hash"`
	NormalizedSQL    types.String  `tfsdk:"normalized_sql"`
	QueryType        types.String  `tfsdk:"query_type"`
	CacheEnabled     types.Bool    `tfsdk:"cache_enabled"`
	CacheTTLSeconds  types.Int64   `tfsdk:"cache_ttl_seconds"`
	CacheSWRSeconds  types.Int64   `tfsdk:"cache_swr_seconds"`
	CallCount        types.Int64   `tfsdk:"call_count"`
	AvgLatencyMs     types.Float64 `tfsdk:"avg_latency_ms"`
	P95LatencyMs     types.Float64 `tfsdk:"p95_latency_ms"`
	AvgResponseBytes types.Int64   `tfsdk:"avg_response_bytes"`
	StabilityRate    types.Float64 `tfsdk:"stability_rate"`
	Recommendation   types.String  `tfsdk:"recommendation"`
	FirstSeenAt      types.String  `tfsdk:"first_seen_at"`
	LastSeenAt       types.String  `tfsdk:"last_seen_at"`
}

func NewCacheRuleResource() resource.Resource {
	return &cacheRuleResource{}
}

func (r *cacheRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cache_rule"
}

func (r *cacheRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a per-query cache rule. Deletion disables caching (soft-delete).",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Composite ID in the format project_id/database_id/query_hash.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "project ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"database_id": schema.StringAttribute{
				Description: "database ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"query_hash": schema.StringAttribute{
				Description: "xxhash64 hex of the normalized SQL.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"normalized_sql": schema.StringAttribute{
				Description: "SQL with literals replaced by $N placeholders.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"query_type": schema.StringAttribute{
				Description: "Query classification.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cache_enabled": schema.BoolAttribute{
				Description: "Whether caching is enabled for this query shape.",
				Required:    true,
			},
			"cache_ttl_seconds": schema.Int64Attribute{
				Description: "TTL override in seconds. Null means use project default.",
				Optional:    true,
			},
			"cache_swr_seconds": schema.Int64Attribute{
				Description: "SWR override in seconds. Null means use project default.",
				Optional:    true,
			},
			"call_count": schema.Int64Attribute{
				Description: "Total number of executions observed.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"avg_latency_ms": schema.Float64Attribute{
				Description: "Average query latency in milliseconds.",
				Computed:    true,
				PlanModifiers: []planmodifier.Float64{
					float64planmodifier.UseStateForUnknown(),
				},
			},
			"p95_latency_ms": schema.Float64Attribute{
				Description: "95th percentile latency in milliseconds.",
				Computed:    true,
				PlanModifiers: []planmodifier.Float64{
					float64planmodifier.UseStateForUnknown(),
				},
			},
			"avg_response_bytes": schema.Int64Attribute{
				Description: "Average response size in bytes.",
				Computed:    true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"stability_rate": schema.Float64Attribute{
				Description: "Response stability rate (0.0 to 1.0). Higher means more stable.",
				Computed:    true,
				PlanModifiers: []planmodifier.Float64{
					float64planmodifier.UseStateForUnknown(),
				},
			},
			"recommendation": schema.StringAttribute{
				Description: "Cache recommendation based on frequency, latency, and stability.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"first_seen_at": schema.StringAttribute{
				Description: "When this query was first observed.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_seen_at": schema.StringAttribute{
				Description: "When this query was last observed.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *cacheRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *cacheRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan cacheRuleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	upsertReq := pgbeam.UpdateCacheRuleRequest{
		CacheEnabled: plan.CacheEnabled.ValueBool(),
	}

	if !plan.CacheTTLSeconds.IsNull() && !plan.CacheTTLSeconds.IsUnknown() {
		v := int(plan.CacheTTLSeconds.ValueInt64())
		upsertReq.CacheTtlSeconds = &v
	}

	if !plan.CacheSWRSeconds.IsNull() && !plan.CacheSWRSeconds.IsUnknown() {
		v := int(plan.CacheSWRSeconds.ValueInt64())
		upsertReq.CacheSwrSeconds = &v
	}

	result, err := r.client.Projects.UpdateCacheRule(ctx, plan.ProjectID.ValueString(), plan.DatabaseID.ValueString(), plan.QueryHash.ValueString(), upsertReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating cache rule", err.Error())
		return
	}

	plan.ID = types.StringValue(plan.ProjectID.ValueString() + "/" + plan.DatabaseID.ValueString() + "/" + plan.QueryHash.ValueString())
	r.mapCacheRuleEntryToState(&plan, &result.Entry)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *cacheRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state cacheRuleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	CacheRuleEntry, err := r.findCacheRuleEntry(ctx, state.ProjectID.ValueString(), state.DatabaseID.ValueString(), state.QueryHash.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading cache rule", err.Error())
		return
	}

	r.mapCacheRuleEntryToState(&state, CacheRuleEntry)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *cacheRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan cacheRuleResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	upsertReq := pgbeam.UpdateCacheRuleRequest{
		CacheEnabled: plan.CacheEnabled.ValueBool(),
	}

	if !plan.CacheTTLSeconds.IsNull() && !plan.CacheTTLSeconds.IsUnknown() {
		v := int(plan.CacheTTLSeconds.ValueInt64())
		upsertReq.CacheTtlSeconds = &v
	}

	if !plan.CacheSWRSeconds.IsNull() && !plan.CacheSWRSeconds.IsUnknown() {
		v := int(plan.CacheSWRSeconds.ValueInt64())
		upsertReq.CacheSwrSeconds = &v
	}

	result, err := r.client.Projects.UpdateCacheRule(ctx, plan.ProjectID.ValueString(), plan.DatabaseID.ValueString(), plan.QueryHash.ValueString(), upsertReq)
	if err != nil {
		resp.Diagnostics.AddError("Error updating cache rule", err.Error())
		return
	}

	r.mapCacheRuleEntryToState(&plan, &result.Entry)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *cacheRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state cacheRuleResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteReq := pgbeam.UpdateCacheRuleRequest{
		CacheEnabled: false,
	}
	_, err := r.client.Projects.UpdateCacheRule(ctx, state.ProjectID.ValueString(), state.DatabaseID.ValueString(), state.QueryHash.ValueString(), deleteReq)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting cache rule", err.Error())
	}
}

func (r *cacheRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 3)
	if len(parts) != 3 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/database_id/query_hash")
		return
	}

	projectID := parts[0]
	databaseID := parts[1]
	queryHash := parts[2]

	CacheRuleEntry, err := r.findCacheRuleEntry(ctx, projectID, databaseID, queryHash)
	if err != nil {
		resp.Diagnostics.AddError("Error importing cache rule", err.Error())
		return
	}

	var state cacheRuleResourceModel
	state.ID = types.StringValue(req.ID)
	state.QueryHash = types.StringValue(queryHash)
	r.mapCacheRuleEntryToState(&state, CacheRuleEntry)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// findCacheRuleEntry lists cache rules and returns the one matching the given query_hash.
// Returns a not-found error if no match is found.
func (r *cacheRuleResource) findCacheRuleEntry(ctx context.Context, projectID string, databaseID string, queryHash string) (*pgbeam.CacheRuleEntry, error) {
	var pageToken *string
	for {
		params := &pgbeam.ListCacheRulesParams{
			PageToken: pageToken,
		}
		listResp, err := r.client.Projects.ListCacheRules(ctx, projectID, databaseID, params)
		if err != nil {
			return nil, err
		}
		for _, CacheRuleEntry := range listResp.Entries {
			if CacheRuleEntry.QueryHash == queryHash {
				return &CacheRuleEntry, nil
			}
		}
		if listResp.NextPageToken == nil || *listResp.NextPageToken == "" {
			break
		}
		pageToken = listResp.NextPageToken
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "404 Not Found", Body: fmt.Sprintf("cache rule %s not found", queryHash)}
}

func (r *cacheRuleResource) mapCacheRuleEntryToState(state *cacheRuleResourceModel, resp *pgbeam.CacheRuleEntry) {
	state.QueryHash = types.StringValue(resp.QueryHash)
	state.NormalizedSQL = types.StringValue(resp.NormalizedSql)
	if string(resp.QueryType) != "" {
		state.QueryType = types.StringValue(string(resp.QueryType))
	} else {
		state.QueryType = types.StringNull()
	}
	state.CacheEnabled = types.BoolValue(resp.CacheEnabled)
	if resp.CacheTtlSeconds != nil {
		state.CacheTTLSeconds = types.Int64Value(int64(*resp.CacheTtlSeconds))
	} else {
		state.CacheTTLSeconds = types.Int64Null()
	}
	if resp.CacheSwrSeconds != nil {
		state.CacheSWRSeconds = types.Int64Value(int64(*resp.CacheSwrSeconds))
	} else {
		state.CacheSWRSeconds = types.Int64Null()
	}
	state.CallCount = types.Int64Value(int64(resp.CallCount))
	state.AvgLatencyMs = types.Float64Value(resp.AvgLatencyMs)
	state.P95LatencyMs = types.Float64Value(resp.P95LatencyMs)
	state.AvgResponseBytes = types.Int64Value(int64(resp.AvgResponseBytes))
	state.StabilityRate = types.Float64Value(resp.StabilityRate)
	if string(resp.Recommendation) != "" {
		state.Recommendation = types.StringValue(string(resp.Recommendation))
	} else {
		state.Recommendation = types.StringNull()
	}
	state.FirstSeenAt = types.StringValue(resp.FirstSeenAt.Format(time.RFC3339))
	state.LastSeenAt = types.StringValue(resp.LastSeenAt.Format(time.RFC3339))
}
