// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ datasource.DataSource              = (*customDomainVerificationDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*customDomainVerificationDataSource)(nil)
)

type customDomainVerificationDataSource struct {
	client *pgbeam.Client
}

type customDomainVerificationDataSourceModel struct {
	ProjectID types.String `tfsdk:"project_id"`
	DomainID  types.String `tfsdk:"domain_id"`
	Verified  types.Bool   `tfsdk:"verified"`
	Error     types.String `tfsdk:"error"`
}

func NewCustomDomainVerificationDataSource() datasource.DataSource {
	return &customDomainVerificationDataSource{}
}

func (d *customDomainVerificationDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_domain_verification"
}

func (d *customDomainVerificationDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Triggers and reads DNS verification for a custom domain.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				Description: "project ID.",
				Required:    true,
			},
			"domain_id": schema.StringAttribute{
				Description: "domain ID.",
				Required:    true,
			},
			"verified": schema.BoolAttribute{
				Description: "Whether DNS verification succeeded.",
				Computed:    true,
			},
			"error": schema.StringAttribute{
				Description: "Error message if verification failed.",
				Computed:    true,
			},
		},
	}
}

func (d *customDomainVerificationDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	d.client = client
}

func (d *customDomainVerificationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data customDomainVerificationDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	result, err := d.client.Projects.VerifyCustomDomain(ctx, data.ProjectID.ValueString(), data.DomainID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error verifying custom domain", err.Error())
		return
	}

	data.Verified = types.BoolValue(result.Verified)
	if result.Error != nil {
		data.Error = types.StringValue(*result.Error)
	} else {
		data.Error = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
