// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "github.com/pgbeam/pgbeam-go"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*customDomainResource)(nil)
	_ resource.ResourceWithConfigure   = (*customDomainResource)(nil)
	_ resource.ResourceWithImportState = (*customDomainResource)(nil)
)

type customDomainResource struct {
	client *pgbeam.Client
}

type customDomainResourceModel struct {
	ID                   types.String `tfsdk:"id"`
	ProjectID            types.String `tfsdk:"project_id"`
	Domain               types.String `tfsdk:"domain"`
	Verified             types.Bool   `tfsdk:"verified"`
	VerifiedAt           types.String `tfsdk:"verified_at"`
	TLSCertExpiry        types.String `tfsdk:"tls_cert_expiry"`
	DNSVerificationToken types.String `tfsdk:"dns_verification_token"`
	DNSInstructions      types.Object `tfsdk:"dns_instructions"`
	CreatedAt            types.String `tfsdk:"created_at"`
	UpdatedAt            types.String `tfsdk:"updated_at"`
}

type dnsInstructionsModel struct {
	CnameHost       types.String `tfsdk:"cname_host"`
	CnameTarget     types.String `tfsdk:"cname_target"`
	TxtHost         types.String `tfsdk:"txt_host"`
	TxtValue        types.String `tfsdk:"txt_value"`
	ACMECnameHost   types.String `tfsdk:"acme_cname_host"`
	ACMECnameTarget types.String `tfsdk:"acme_cname_target"`
}

func NewCustomDomainResource() resource.Resource {
	return &customDomainResource{}
}

func dnsInstructionsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"cname_host":        types.StringType,
		"cname_target":      types.StringType,
		"txt_host":          types.StringType,
		"txt_value":         types.StringType,
		"acme_cname_host":   types.StringType,
		"acme_cname_target": types.StringType,
	}
}

func (r *customDomainResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_domain"
}

func (r *customDomainResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a custom domain for a PgBeam project.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique domain identifier (prefixed).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "Owning project ID.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"domain": schema.StringAttribute{
				Description: "The custom domain name.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"verified": schema.BoolAttribute{
				Description: "Whether DNS ownership has been verified.",
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"verified_at": schema.StringAttribute{
				Description: "When DNS verification was completed.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"tls_cert_expiry": schema.StringAttribute{
				Description: "When the TLS certificate expires.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"dns_verification_token": schema.StringAttribute{
				Description: "Token value for the DNS TXT record verification.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"dns_instructions": schema.SingleNestedAttribute{
				Description: "DNS records the user needs to create for domain verification.",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"cname_host": schema.StringAttribute{
						Description: "The CNAME record host.",
						Optional:    true,
					},
					"cname_target": schema.StringAttribute{
						Description: "The CNAME record target.",
						Optional:    true,
					},
					"txt_host": schema.StringAttribute{
						Description: "The TXT record host for verification.",
						Optional:    true,
					},
					"txt_value": schema.StringAttribute{
						Description: "The TXT record value for verification.",
						Optional:    true,
					},
					"acme_cname_host": schema.StringAttribute{
						Description: "The CNAME record host for ACME TLS certificate issuance.",
						Optional:    true,
					},
					"acme_cname_target": schema.StringAttribute{
						Description: "The CNAME target for ACME challenge delegation.",
						Optional:    true,
					},
				},
			},
			"created_at": schema.StringAttribute{
				Description: "When the custom domain was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the custom domain was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *customDomainResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *customDomainResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan customDomainResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.CreateCustomDomainRequest{
		Domain: plan.Domain.ValueString(),
	}

	result, err := r.client.Projects.CreateCustomDomain(ctx, plan.ProjectID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating custom domain", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Id)
	r.mapCustomDomainToState(ctx, &plan, result, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *customDomainResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state customDomainResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	CustomDomain, err := r.findCustomDomain(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading custom domain", err.Error())
		return
	}

	r.mapCustomDomainToState(ctx, &state, CustomDomain, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update is not implemented — all fields RequiresReplace, so Terraform will
// never call Update. It is included to satisfy the Resource interface.
func (r *customDomainResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update Not Supported", "CustomDomain resources are immutable. All changes trigger a replacement.")
}

func (r *customDomainResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state customDomainResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Projects.DeleteCustomDomain(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting custom domain", err.Error())
	}
}

func (r *customDomainResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/domain_id")
		return
	}

	projectID := parts[0]
	domainID := parts[1]

	CustomDomain, err := r.findCustomDomain(ctx, projectID, domainID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing custom domain", err.Error())
		return
	}

	var state customDomainResourceModel
	state.ID = types.StringValue(CustomDomain.Id)
	state.ProjectID = types.StringValue(projectID)
	r.mapCustomDomainToState(ctx, &state, CustomDomain, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// findCustomDomain lists custom domains and returns the one matching the given id.
// Returns a not-found error if no match is found.
func (r *customDomainResource) findCustomDomain(ctx context.Context, projectID string, CustomDomainID string) (*pgbeam.CustomDomain, error) {
	var pageToken *string
	for {
		params := &pgbeam.ListCustomDomainsParams{
			PageToken: pageToken,
		}
		listResp, err := r.client.Projects.ListCustomDomains(ctx, projectID, params)
		if err != nil {
			return nil, err
		}
		for _, CustomDomain := range listResp.Domains {
			if CustomDomain.Id == CustomDomainID {
				return &CustomDomain, nil
			}
		}
		if listResp.NextPageToken == nil || *listResp.NextPageToken == "" {
			break
		}
		pageToken = listResp.NextPageToken
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "404 Not Found", Body: fmt.Sprintf("custom domain %s not found", CustomDomainID)}
}

func (r *customDomainResource) mapCustomDomainToState(ctx context.Context, state *customDomainResourceModel, resp *pgbeam.CustomDomain, diags *diag.Diagnostics) {
	state.ProjectID = types.StringValue(resp.ProjectId)
	state.Domain = types.StringValue(resp.Domain)
	state.Verified = types.BoolValue(resp.Verified)
	if resp.VerifiedAt != nil {
		state.VerifiedAt = types.StringValue(resp.VerifiedAt.Format(time.RFC3339))
	} else {
		state.VerifiedAt = types.StringNull()
	}
	if resp.TlsCertExpiry != nil {
		state.TLSCertExpiry = types.StringValue(resp.TlsCertExpiry.Format(time.RFC3339))
	} else {
		state.TLSCertExpiry = types.StringNull()
	}
	state.DNSVerificationToken = types.StringValue(resp.DnsVerificationToken)
	if resp.DnsInstructions != nil {
		obj, d := types.ObjectValue(dnsInstructionsAttrTypes(), map[string]attr.Value{
			"cname_host":        optionalStringValue(resp.DnsInstructions.CnameHost),
			"cname_target":      optionalStringValue(resp.DnsInstructions.CnameTarget),
			"txt_host":          optionalStringValue(resp.DnsInstructions.TxtHost),
			"txt_value":         optionalStringValue(resp.DnsInstructions.TxtValue),
			"acme_cname_host":   optionalStringValue(resp.DnsInstructions.AcmeCnameHost),
			"acme_cname_target": optionalStringValue(resp.DnsInstructions.AcmeCnameTarget),
		})
		diags.Append(d...)
		state.DNSInstructions = obj
	} else {
		state.DNSInstructions = types.ObjectNull(dnsInstructionsAttrTypes())
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}

// optionalStringValue converts a *string to a types.String, using empty string for nil.
func optionalStringValue(s *string) types.String {
	if s != nil {
		return types.StringValue(*s)
	}
	return types.StringValue("")
}
