// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*honeytokenResource)(nil)
	_ resource.ResourceWithConfigure   = (*honeytokenResource)(nil)
	_ resource.ResourceWithImportState = (*honeytokenResource)(nil)
)

type honeytokenResource struct {
	client *pgbeam.Client
}

type honeytokenResourceModel struct {
	ID           types.String `tfsdk:"id"`
	ProjectID    types.String `tfsdk:"project_id"`
	SchemaName   types.String `tfsdk:"schema_name"`
	RelationName types.String `tfsdk:"relation_name"`
	Action       types.String `tfsdk:"action"`
	CreatedAt    types.String `tfsdk:"created_at"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
}

func NewHoneytokenResource() resource.Resource {
	return &honeytokenResource{}
}

func (r *honeytokenResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_honeytoken"
}

func (r *honeytokenResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a honeytoken: a decoy (canary) relation that no legitimate query should ever touch. Any agent statement referencing it is blocked and recorded as a canary_tripped audit event; the kill action additionally disables the tripping credential via the kill-switch. The relation does not have to exist in the upstream database: enforcement is by name, in the wire protocol, before the statement reaches Postgres.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique honeytoken identifier.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"project_id": schema.StringAttribute{
				Description: "Project the honeytoken belongs to.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"schema_name": schema.StringAttribute{
				Description: "Optional schema. Null matches the unqualified/public form, mirroring the relation allowlist normalization.\n",
				Optional:    true,
			},
			"relation_name": schema.StringAttribute{
				Description: "Relation (table or view) name of the decoy.",
				Required:    true,
			},
			"action": schema.StringAttribute{
				Description: "Response when tripped. audit_only blocks the statement, records the event, and fires webhooks. kill additionally disables the tripping credential via the kill-switch.\n",
				Required:    true,
			},
			"created_at": schema.StringAttribute{
				Description: "When the honeytoken was registered.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the honeytoken was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *honeytokenResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *honeytokenResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan honeytokenResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.HoneytokenInput{
		RelationName: plan.RelationName.ValueString(),
		Action:       pgbeam.HoneytokenInputAction(plan.Action.ValueString()),
	}

	if !plan.SchemaName.IsNull() && !plan.SchemaName.IsUnknown() {
		v := plan.SchemaName.ValueString()
		createReq.SchemaName = &v
	}

	result, err := r.client.Honeytokens.CreateHoneytoken(ctx, plan.ProjectID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating honeytoken", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Id)
	r.mapHoneytokenToState(&plan, result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *honeytokenResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state honeytokenResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	Honeytoken, err := r.client.Honeytokens.GetHoneytoken(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading honeytoken", err.Error())
		return
	}

	r.mapHoneytokenToState(&state, Honeytoken)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *honeytokenResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan honeytokenResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var state honeytokenResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	hasChanges := !plan.SchemaName.Equal(state.SchemaName) ||
		!plan.RelationName.Equal(state.RelationName) ||
		!plan.Action.Equal(state.Action)

	updateReq := pgbeam.HoneytokenInput{
		RelationName: plan.RelationName.ValueString(),
		Action:       pgbeam.HoneytokenInputAction(plan.Action.ValueString()),
	}

	if !plan.SchemaName.IsNull() && !plan.SchemaName.IsUnknown() {
		v := plan.SchemaName.ValueString()
		updateReq.SchemaName = &v
	}

	if hasChanges {
		_, err := r.client.Honeytokens.UpdateHoneytoken(ctx, state.ProjectID.ValueString(), state.ID.ValueString(), updateReq)
		if err != nil {
			resp.Diagnostics.AddError("Error updating honeytoken", err.Error())
			return
		}
	}

	Honeytoken, err := r.client.Honeytokens.GetHoneytoken(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Error reading honeytoken after update", err.Error())
		return
	}

	plan.ID = state.ID
	r.mapHoneytokenToState(&plan, Honeytoken)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *honeytokenResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state honeytokenResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Honeytokens.DeleteHoneytoken(ctx, state.ProjectID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting honeytoken", err.Error())
	}
}

func (r *honeytokenResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: project_id/honeytoken_id")
		return
	}

	projectID := parts[0]
	honeytokenID := parts[1]

	Honeytoken, err := r.client.Honeytokens.GetHoneytoken(ctx, projectID, honeytokenID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing honeytoken", err.Error())
		return
	}

	var state honeytokenResourceModel
	state.ID = types.StringValue(Honeytoken.Id)
	state.ProjectID = types.StringValue(projectID)
	r.mapHoneytokenToState(&state, Honeytoken)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *honeytokenResource) mapHoneytokenToState(state *honeytokenResourceModel, resp *pgbeam.Honeytoken) {
	state.ProjectID = types.StringValue(resp.ProjectId)
	if resp.SchemaName != nil {
		state.SchemaName = types.StringValue(*resp.SchemaName)
	} else {
		state.SchemaName = types.StringNull()
	}
	state.RelationName = types.StringValue(resp.RelationName)
	if string(resp.Action) != "" {
		state.Action = types.StringValue(string(resp.Action))
	} else {
		state.Action = types.StringNull()
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
}
