// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/datasource"

func pgbeamDataSources() []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewCustomDomainVerificationDataSource,
	}
}
