// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "go.pgbeam.com/sdk"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*selfHostEnrollmentResource)(nil)
	_ resource.ResourceWithConfigure   = (*selfHostEnrollmentResource)(nil)
	_ resource.ResourceWithImportState = (*selfHostEnrollmentResource)(nil)
)

type selfHostEnrollmentResource struct {
	client *pgbeam.Client
}

type selfHostEnrollmentResourceModel struct {
	ID          types.String `tfsdk:"id"`
	OrgID       types.String `tfsdk:"org_id"`
	RegionLabel types.String `tfsdk:"region_label"`
	Description types.String `tfsdk:"description"`
	CreatedBy   types.String `tfsdk:"created_by"`
	CreatedAt   types.String `tfsdk:"created_at"`
	LastSeenAt  types.String `tfsdk:"last_seen_at"`
	RevokedAt   types.String `tfsdk:"revoked_at"`
	ExpiresAt   types.String `tfsdk:"expires_at"`
	Token       types.String `tfsdk:"token"`
}

func NewSelfHostEnrollmentResource() resource.Resource {
	return &selfHostEnrollmentResource{}
}

func (r *selfHostEnrollmentResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_self_host_enrollment"
}

func (r *selfHostEnrollmentResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a self-host (BYOC) enrollment: a token a self-hosted proxy uses to authenticate to the control plane's config/audit stream. The token is a one-time secret returned only at creation and exposed as a sensitive computed output; it cannot be retrieved again. To rotate the token, replace the resource. Deletion revokes the enrollment.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Unique enrollment identifier.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"org_id": schema.StringAttribute{
				Description: "Organization that owns this enrollment.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"region_label": schema.StringAttribute{
				Description: "Operator-supplied label for where the proxy runs (informational).",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"description": schema.StringAttribute{
				Description: "Optional human-readable note.",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"created_by": schema.StringAttribute{
				Description: "User ID that created the enrollment.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"created_at": schema.StringAttribute{
				Description: "When the enrollment was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_seen_at": schema.StringAttribute{
				Description: "Last time a proxy authenticated with this enrollment.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"revoked_at": schema.StringAttribute{
				Description: "When the enrollment was revoked. Null means active.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"expires_at": schema.StringAttribute{
				Description: "When the enrollment token expires and stops authenticating new proxy connections. Null means it never expires. Enforcement is fail-closed at the gRPC auth gate the instant this time passes.",
				Optional:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"token": schema.StringAttribute{
				Description: "One-time enrollment token (pbh_...) for the self-hosted proxy's GRPC_AUTH_TOKEN (shown once).",
				Computed:    true,
				Sensitive:   true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *selfHostEnrollmentResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *selfHostEnrollmentResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan selfHostEnrollmentResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createReq := pgbeam.CreateSelfHostEnrollmentRequest{}

	if !plan.RegionLabel.IsNull() && !plan.RegionLabel.IsUnknown() {
		v := plan.RegionLabel.ValueString()
		createReq.RegionLabel = &v
	}

	if !plan.Description.IsNull() && !plan.Description.IsUnknown() {
		v := plan.Description.ValueString()
		createReq.Description = &v
	}

	if !plan.ExpiresAt.IsNull() && !plan.ExpiresAt.IsUnknown() {
		expiresAtTime, err := time.Parse(time.RFC3339, plan.ExpiresAt.ValueString())
		if err != nil {
			resp.Diagnostics.AddError("Invalid expires_at", "Expected an RFC3339 timestamp: "+err.Error())
			return
		}
		createReq.ExpiresAt = &expiresAtTime
	}

	result, err := r.client.Platform.CreateSelfHostEnrollment(ctx, plan.OrgID.ValueString(), createReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating self host enrollment", err.Error())
		return
	}

	plan.ID = types.StringValue(result.Enrollment.Id)
	r.mapSelfHostEnrollmentToState(&plan, &result.Enrollment)

	plan.Token = types.StringValue(result.Token)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *selfHostEnrollmentResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state selfHostEnrollmentResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	SelfHostEnrollment, err := r.findSelfHostEnrollment(ctx, state.OrgID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading self host enrollment", err.Error())
		return
	}

	r.mapSelfHostEnrollmentToState(&state, SelfHostEnrollment)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// Update is not implemented — all fields RequiresReplace, so Terraform will
// never call Update. It is included to satisfy the Resource interface.
func (r *selfHostEnrollmentResource) Update(_ context.Context, _ resource.UpdateRequest, resp *resource.UpdateResponse) {
	resp.Diagnostics.AddError("Update Not Supported", "SelfHostEnrollment resources are immutable. All changes trigger a replacement.")
}

func (r *selfHostEnrollmentResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state selfHostEnrollmentResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.Platform.RevokeSelfHostEnrollment(ctx, state.OrgID.ValueString(), state.ID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting self host enrollment", err.Error())
	}
}

func (r *selfHostEnrollmentResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	parts := strings.SplitN(req.ID, "/", 2)
	if len(parts) != 2 {
		resp.Diagnostics.AddError("Invalid Import ID", "Expected format: org_id/enrollment_id")
		return
	}

	orgID := parts[0]
	enrollmentID := parts[1]

	SelfHostEnrollment, err := r.findSelfHostEnrollment(ctx, orgID, enrollmentID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing self host enrollment", err.Error())
		return
	}

	var state selfHostEnrollmentResourceModel
	state.ID = types.StringValue(SelfHostEnrollment.Id)
	state.OrgID = types.StringValue(orgID)
	r.mapSelfHostEnrollmentToState(&state, SelfHostEnrollment)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

// findSelfHostEnrollment lists self host enrollments and returns the one matching the given id.
// Returns a not-found error if no match is found.
func (r *selfHostEnrollmentResource) findSelfHostEnrollment(ctx context.Context, orgID string, SelfHostEnrollmentID string) (*pgbeam.SelfHostEnrollment, error) {
	listResp, err := r.client.Platform.ListSelfHostEnrollments(ctx, orgID)
	if err != nil {
		return nil, err
	}
	for _, SelfHostEnrollment := range listResp.Enrollments {
		if SelfHostEnrollment.Id == SelfHostEnrollmentID {
			return &SelfHostEnrollment, nil
		}
	}
	return nil, &pgbeam.APIError{StatusCode: 404, Status: "404 Not Found", Body: fmt.Sprintf("self host enrollment %s not found", SelfHostEnrollmentID)}
}

func (r *selfHostEnrollmentResource) mapSelfHostEnrollmentToState(state *selfHostEnrollmentResourceModel, resp *pgbeam.SelfHostEnrollment) {
	state.OrgID = types.StringValue(resp.OrgId)
	if resp.RegionLabel != nil {
		state.RegionLabel = types.StringValue(*resp.RegionLabel)
	} else {
		state.RegionLabel = types.StringNull()
	}
	if resp.Description != nil {
		state.Description = types.StringValue(*resp.Description)
	} else {
		state.Description = types.StringNull()
	}
	if resp.CreatedBy != nil {
		state.CreatedBy = types.StringValue(*resp.CreatedBy)
	} else {
		state.CreatedBy = types.StringNull()
	}
	state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	if resp.LastSeenAt != nil {
		state.LastSeenAt = types.StringValue(resp.LastSeenAt.Format(time.RFC3339))
	} else {
		state.LastSeenAt = types.StringNull()
	}
	if resp.RevokedAt != nil {
		state.RevokedAt = types.StringValue(resp.RevokedAt.Format(time.RFC3339))
	} else {
		state.RevokedAt = types.StringNull()
	}
	if resp.ExpiresAt != nil {
		state.ExpiresAt = types.StringValue(resp.ExpiresAt.Format(time.RFC3339))
	} else {
		state.ExpiresAt = types.StringNull()
	}
}
