// Code generated by generate-terraform.ts — DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"time"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	pgbeam "github.com/pgbeam/pgbeam-go"
)

var (
	_ = fmt.Sprintf
	_ = time.RFC3339
)

var (
	_ resource.Resource                = (*spendLimitResource)(nil)
	_ resource.ResourceWithConfigure   = (*spendLimitResource)(nil)
	_ resource.ResourceWithImportState = (*spendLimitResource)(nil)
)

type spendLimitResource struct {
	client *pgbeam.Client
}

type spendLimitResourceModel struct {
	ID                 types.String  `tfsdk:"id"`
	OrgID              types.String  `tfsdk:"org_id"`
	Plan               types.String  `tfsdk:"plan"`
	BillingProvider    types.String  `tfsdk:"billing_provider"`
	SubscriptionStatus types.String  `tfsdk:"subscription_status"`
	CurrentPeriodEnd   types.String  `tfsdk:"current_period_end"`
	Enabled            types.Bool    `tfsdk:"enabled"`
	CustomPricing      types.Bool    `tfsdk:"custom_pricing"`
	SpendLimit         types.Float64 `tfsdk:"spend_limit"`
	Limits             types.Object  `tfsdk:"limits"`
	CreatedAt          types.String  `tfsdk:"created_at"`
	UpdatedAt          types.String  `tfsdk:"updated_at"`
}

type limitsModel struct {
	QueriesPerDay    types.Int64 `tfsdk:"queries_per_day"`
	MaxProjects      types.Int64 `tfsdk:"max_projects"`
	MaxDatabases     types.Int64 `tfsdk:"max_databases"`
	MaxConnections   types.Int64 `tfsdk:"max_connections"`
	QueriesPerSecond types.Int64 `tfsdk:"queries_per_second"`
	BytesPerMonth    types.Int64 `tfsdk:"bytes_per_month"`
	MaxQueryShapes   types.Int64 `tfsdk:"max_query_shapes"`
	IncludedSeats    types.Int64 `tfsdk:"included_seats"`
}

func NewSpendLimitResource() resource.Resource {
	return &spendLimitResource{}
}

func limitsAttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"queries_per_day":    types.Int64Type,
		"max_projects":       types.Int64Type,
		"max_databases":      types.Int64Type,
		"max_connections":    types.Int64Type,
		"queries_per_second": types.Int64Type,
		"bytes_per_month":    types.Int64Type,
		"max_query_shapes":   types.Int64Type,
		"included_seats":     types.Int64Type,
	}
}

func (r *spendLimitResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_spend_limit"
}

func (r *spendLimitResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages the monthly spend limit for an organization.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Description: "Resource ID.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"org_id": schema.StringAttribute{
				Description: "Organization identifier the plan applies to.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"plan": schema.StringAttribute{
				Description: "Current plan tier.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"billing_provider": schema.StringAttribute{
				Description: "Which billing provider manages this organization's subscription.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"subscription_status": schema.StringAttribute{
				Description: "Stripe subscription status.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"current_period_end": schema.StringAttribute{
				Description: "End of current billing period.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"enabled": schema.BoolAttribute{
				Description: "Whether the organization billing is active (false = suspended).",
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"custom_pricing": schema.BoolAttribute{
				Description: "Whether the organization has custom enterprise pricing.",
				Computed:    true,
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"spend_limit": schema.Float64Attribute{
				Description: "Monthly spend limit in dollars. Null means no limit.",
				Optional:    true,
			},
			"limits": schema.SingleNestedAttribute{
				Description: "Effective usage limits enforced for an organization plan.",
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"queries_per_day": schema.Int64Attribute{
						Description: "Maximum queries per day across all projects. 0 means unlimited.",
						Required:    true,
					},
					"max_projects": schema.Int64Attribute{
						Description: "Maximum number of active projects.",
						Required:    true,
					},
					"max_databases": schema.Int64Attribute{
						Description: "Maximum databases per project.",
						Required:    true,
					},
					"max_connections": schema.Int64Attribute{
						Description: "Maximum concurrent connections per project.",
						Required:    true,
					},
					"queries_per_second": schema.Int64Attribute{
						Description: "Maximum queries per second per project.",
						Required:    true,
					},
					"bytes_per_month": schema.Int64Attribute{
						Description: "Monthly data transfer quota in bytes. 0 means unlimited.",
						Required:    true,
					},
					"max_query_shapes": schema.Int64Attribute{
						Description: "Maximum query shapes in cache rules. 0 means unlimited.",
						Required:    true,
					},
					"included_seats": schema.Int64Attribute{
						Description: "Number of seats included in the plan.",
						Required:    true,
					},
				},
			},
			"created_at": schema.StringAttribute{
				Description: "When the billing record was created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"updated_at": schema.StringAttribute{
				Description: "When the billing record was last updated.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *spendLimitResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*pgbeam.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type", fmt.Sprintf("Expected *pgbeam.Client, got: %T", req.ProviderData))
		return
	}
	r.client = client
}

func (r *spendLimitResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan spendLimitResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	upsertReq := pgbeam.UpdateSpendLimitRequest{}

	if !plan.SpendLimit.IsNull() && !plan.SpendLimit.IsUnknown() {
		v := plan.SpendLimit.ValueFloat64()
		upsertReq.SpendLimit = &v
	}

	result, err := r.client.Analytics.UpdateSpendLimit(ctx, plan.OrgID.ValueString(), upsertReq)
	if err != nil {
		resp.Diagnostics.AddError("Error creating spend limit", err.Error())
		return
	}

	plan.ID = types.StringValue(plan.OrgID.ValueString())
	r.mapOrganizationPlanToState(ctx, &plan, result, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *spendLimitResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state spendLimitResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	OrganizationPlan, err := r.client.Analytics.GetOrganizationPlan(ctx, state.OrgID.ValueString())
	if err != nil {
		if pgbeam.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading spend limit", err.Error())
		return
	}

	r.mapOrganizationPlanToState(ctx, &state, OrganizationPlan, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *spendLimitResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan spendLimitResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	upsertReq := pgbeam.UpdateSpendLimitRequest{}

	if !plan.SpendLimit.IsNull() && !plan.SpendLimit.IsUnknown() {
		v := plan.SpendLimit.ValueFloat64()
		upsertReq.SpendLimit = &v
	}

	result, err := r.client.Analytics.UpdateSpendLimit(ctx, plan.OrgID.ValueString(), upsertReq)
	if err != nil {
		resp.Diagnostics.AddError("Error updating spend limit", err.Error())
		return
	}

	r.mapOrganizationPlanToState(ctx, &plan, result, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *spendLimitResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state spendLimitResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteReq := pgbeam.UpdateSpendLimitRequest{
		SpendLimit: nil,
	}
	_, err := r.client.Analytics.UpdateSpendLimit(ctx, state.OrgID.ValueString(), deleteReq)
	if err != nil {
		if pgbeam.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting spend limit", err.Error())
	}
}

func (r *spendLimitResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	OrganizationPlan, err := r.client.Analytics.GetOrganizationPlan(ctx, req.ID)
	if err != nil {
		resp.Diagnostics.AddError("Error importing spend limit", err.Error())
		return
	}

	var state spendLimitResourceModel
	state.ID = types.StringValue(OrganizationPlan.OrgId)
	r.mapOrganizationPlanToState(ctx, &state, OrganizationPlan, &resp.Diagnostics)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *spendLimitResource) mapOrganizationPlanToState(ctx context.Context, state *spendLimitResourceModel, resp *pgbeam.OrganizationPlan, diags *diag.Diagnostics) {
	state.OrgID = types.StringValue(resp.OrgId)
	if string(resp.Plan) != "" {
		state.Plan = types.StringValue(string(resp.Plan))
	} else {
		state.Plan = types.StringNull()
	}
	if resp.BillingProvider != nil && string(*resp.BillingProvider) != "" {
		state.BillingProvider = types.StringValue(string(*resp.BillingProvider))
	} else {
		state.BillingProvider = types.StringNull()
	}
	if resp.SubscriptionStatus != nil && string(*resp.SubscriptionStatus) != "" {
		state.SubscriptionStatus = types.StringValue(string(*resp.SubscriptionStatus))
	} else {
		state.SubscriptionStatus = types.StringNull()
	}
	if resp.CurrentPeriodEnd != nil {
		state.CurrentPeriodEnd = types.StringValue(resp.CurrentPeriodEnd.Format(time.RFC3339))
	} else {
		state.CurrentPeriodEnd = types.StringNull()
	}
	if resp.Enabled != nil {
		state.Enabled = types.BoolValue(*resp.Enabled)
	} else {
		state.Enabled = types.BoolNull()
	}
	if resp.CustomPricing != nil {
		state.CustomPricing = types.BoolValue(*resp.CustomPricing)
	} else {
		state.CustomPricing = types.BoolNull()
	}
	if resp.SpendLimit != nil {
		state.SpendLimit = types.Float64Value(*resp.SpendLimit)
	} else {
		state.SpendLimit = types.Float64Null()
	}
	obj, d := types.ObjectValue(limitsAttrTypes(), map[string]attr.Value{
		"queries_per_day":    types.Int64Value(int64(resp.Limits.QueriesPerDay)),
		"max_projects":       types.Int64Value(int64(resp.Limits.MaxProjects)),
		"max_databases":      types.Int64Value(int64(resp.Limits.MaxDatabases)),
		"max_connections":    types.Int64Value(int64(resp.Limits.MaxConnections)),
		"queries_per_second": types.Int64Value(int64(resp.Limits.QueriesPerSecond)),
		"bytes_per_month":    types.Int64Value(int64(resp.Limits.BytesPerMonth)),
		"max_query_shapes":   types.Int64Value(int64(resp.Limits.MaxQueryShapes)),
		"included_seats":     types.Int64Value(int64(resp.Limits.IncludedSeats)),
	})
	diags.Append(d...)
	state.Limits = obj
	if resp.CreatedAt != nil {
		state.CreatedAt = types.StringValue(resp.CreatedAt.Format(time.RFC3339))
	} else {
		state.CreatedAt = types.StringNull()
	}
	if resp.UpdatedAt != nil {
		state.UpdatedAt = types.StringValue(resp.UpdatedAt.Format(time.RFC3339))
	} else {
		state.UpdatedAt = types.StringNull()
	}
}
